apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
configMapGenerator:
- behavior: merge
  env: overlays/minioPd/params.env
  name: pipeline-minio-parameters
configurations:
- overlays/minioPd/params.yaml
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- overlays/minioPd/persistent-volume-claim.yaml
resources:
- overlays/minioPd/persistent-volume.yaml
vars:
- fieldref:
    fieldPath: data.minioPd
  name: minioPd
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-minio-parameters
- fieldref:
    fieldPath: data.minioPvName
  name: minioPvName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-minio-parameters
