apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
configMapGenerator:
- behavior: merge
  env: overlays/istio/params.env
  name: parameters
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- overlays/istio/deployment.yaml
