apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"certmanager.k8s.io/v1alpha1","kind":"Certificate","metadata":{"annotations":{},"name":"apps-devsandbox-tls","namespace":"istio-system"},"spec":{"acme":{"config":[{"domains":["dev-apps.devsandbox.co"],"http01":{"ingressClass":"istio"}}]},"commonName":"dev-apps.devsandbox.co","dnsNames":["dev-apps.devsandbox.co"],"issuerRef":{"name":"letsencrypt-production-issuer"},"secretName":"apps-devsandbox-tls"}}
  creationTimestamp: 2019-07-12T03:05:30Z
  generation: 3
  name: apps-devsandbox-tls
  namespace: istio-system
  resourceVersion: "61121"
  selfLink: /apis/certmanager.k8s.io/v1alpha1/namespaces/istio-system/certificates/apps-devsandbox-tls
  uid: e8677b66-a451-11e9-8e6f-42010a8e01fb
spec:
  acme:
    config:
    - domains:
      - dev-apps.devsandbox.co
      http01:
        ingress: ""
        ingressClass: istio
  commonName: dev-apps.devsandbox.co
  dnsNames:
  - dev-apps.devsandbox.co
  issuerRef:
    name: letsencrypt-production-issuer
  secretName: apps-devsandbox-tls
status:
  conditions:
  - lastTransitionTime: 2019-07-12T03:15:18Z
    message: Certificate is up to date and has not expired
    reason: Ready
    status: "True"
    type: Ready
  notAfter: 2019-10-10T02:15:17Z
